### ISSUE TITLE
Incompatible with Ecto 2.2

### ISSUE THREAD

**Issue by pinx** [ArangoDB-Community/arangodb_ecto#2]
Scenario:
- create a fresh app with `mix phx.new`
- run `mix phx.gen.schema` to set up a migration file
- add arangodb_ecto as dependency
- replace Postgres adapter with ArangoDB.Ecto
- run `mix ecto.migrate`

This error is thrown:
```
15:41:14.473 [error] Could not retrieve migrated versions. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :test, Test.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (FunctionClauseError) no function clause matching in ArangoDB.Ecto.Adapter.execute/6    
    (elixir) lib/keyword.ex:504: Keyword.delete_key/3
    (elixir) lib/keyword.ex:501: Keyword.delete_key/3
    (elixir) lib/keyword.ex:501: Keyword.delete_key/3
    (elixir) lib/keyword.ex:493: Keyword.put/3
    lib/test/repo.ex:9: Test.Repo.init/2
    (ecto) lib/ecto/repo/supervisor.ex:23: Ecto.Repo.Supervisor.runtime_config/4
    lib/test/repo.ex:2: Test.Repo.config/0
    (ecto) lib/ecto/migrator.ex:316: Ecto.Migrator.verbose_schema_migration/3
    (ecto) lib/ecto/migrator.ex:157: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:83: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
```

**Comment by mpoeter** [comment]
Thanks for raising this issue @pinx!

This seems to bee an issue with Ecto 2.2. I have started to work on this with Ecto 2.1 and did not yet try to use it with Ecto 2.2.

To workaround this, please switch to Ecto 2.1 for now.
